### ISSUE TITLE
Users have profile images

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-server#120]
## User Story
Needed for: https://github.com/boolean-uk/team-dev-client/issues/194

## Tasks
- update the schema
- generate the migration
- update the create/update/read endpoints for users to support profile images

## Check List
**Before PR**
- [ ] Have tested locally using ThunderClient/Postman/etc.
- [ ] For any new APIs, have documented in the README.md
- [ ] Have included and tested any required schema changes
- [ ] Have handled all error cases (try/catch, checked user input, etc.)
- [ ] Error messages are consistent with the rest of the code
- [ ] Correct HTTP Response codes and verbs are used
- [ ] Code confirms to the existing style and structure
- [ ] No warnings or errors are reported when using the API
- [ ] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [ ] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any required schema updates have been applied cleanly
- [ ] If modifying an existing API the client app already uses, have verified the deployed client app still works as expected

**Comment by sigristarisa** [comment]
We have planned this feature, the steps are down below:

- Update the Profile model in the schema
- add “profile_image” with a data type String. Add a default value (url) as a default image *(@default(http://fwejflkwjelkjeflkjwle.jpg/))*
- migrate the schema
- in domain/user.js, add the data “profile_image” in User class in every method
- Test with Insomnia if the profile image is added
https://www.notion.so/Users-have-Profile-Images-78f80dbf2f5c4fdda5c6156551235db9

**Comment by dearshrewdwit** [comment]
Nice. 

Can you give me an example request you will send to **create** a user profile with an image?
Can you give me an example request you will send to **update** a user profile with an image?
