### ISSUE TITLE
Cohorts have start & end dates [5]

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-server#143]
Needed for https://github.com/boolean-uk/team-dev-client/issues/220

## User Story
As a teacher, so I can know how many cohorts we have each year, I want to be able to see the start and end dates of a cohort

## Tasks
[Add your technical tasks here]

## Check List
**Before PR**
- [ ] Have tested locally using ThunderClient/Postman/etc.
- [ ] For any new APIs, have documented in the README.md
- [ ] Have included and tested any required schema changes
- [ ] Have handled all error cases (try/catch, checked user input, etc.)
- [ ] Error messages are consistent with the rest of the code
- [ ] Correct HTTP Response codes and verbs are used
- [ ] Code confirms to the existing style and structure
- [ ] No warnings or errors are reported when using the API
- [ ] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [ ] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any required schema updates have been applied cleanly
- [ ] If modifying an existing API the client app already uses, have verified the deployed client app still works as expected

**Comment by Anicaaa** [comment]
This is our planning https://www.notion.so/Cohorts-have-start-end-dates-5-143-0f8d342781e54049b2fe8fd094dbf64e

**Comment by dearshrewdwit** [comment]
Great start. So far so good.

Let's add a few more steps here. Here's the current data in the table.
![Screenshot 2022-07-06 at 13 05 27](https://user-images.githubusercontent.com/13719921/177546111-da6f5f92-dddd-44fc-bdc9-d6b544364e12.png)

Let's add start and end date data for each cohort in the table.

1. Jan 1st - Jul 1st
2. Feb 1st - Aug 1st
3. Mar 1st - Set 1st
4. Apr 1st. - Oct 1st
5. May 1st - Nov 1st
6. June 1st - Dec 1st
7. July 1st. - Jan 1st '23

Then. Let's add a constraint to the table for the columns start date and end date: NOT NULL.

**Comment by dearshrewdwit** [comment]
See these migrations for reference: 
0. Adding column no constraints: https://github.com/boolean-uk/team-dev-server/blob/main/prisma/migrations/20220628162644_cohort_name_unique_added_to_cohort_model/migration.sql
1. updating data in a table: https://github.com/boolean-uk/team-dev-server/blob/main/prisma/migrations/20220629151021_update_cohort_names_existing_records/migration.sql
2. adding the constraint: https://github.com/boolean-uk/team-dev-server/blob/main/prisma/migrations/20220629161241_cohort_name_unique_constraint/migration.sql
