### ISSUE TITLE
create endpoints for student notes. (SERVER) [3]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#152]
## Story

As a teacher, I want to be able to add notes on individual students.

## Tasks

 - create /profile/:id/notes endpoint (SERVER)
 - create all CRUD endpoints for profile/:id/notes

**Comment by d-username** [comment]
WE WOULD LIKE TO WORK ON CREATE AND DELETE FIRST, AND THEN  IF THIS WORKS AND APPROVED WE WOULD MOVE FORWARD TO THE UPDATE.

**TO CREATE A NOTE:** 

- start in **index.js** adding routes, then create files in **routes** leading to the **controllers**
- in new file **notes.js —>** create the CRUD functions accessing the DB.
- we will get the note content from the req.body
- in a try/catch block —> if no note content then throw error with a message.
- we create the note in Prisma
- and save the note via the save()
- respond to the client with 201 and the created note
- return 400, and an error message if error was caught

**TO DELETE A NOTE:**

- start in **index.js** adding routes, then create files in **routes** leading to the **controllers**
- in new file **notes.js —>** create the CRUD functions accessing the DB.
- we get the noteId from req.params
- in a try/catch block —>if noteId not provided then throw Error with a message
- if noteId provided —> delete the note in DB via Prism `(const data = await Note.delete(noteId))`
- respond to the client with 200 and data.
- return 400, and an error message if error was caught

**Comment by dogezen** [comment]
To CREATE a NOTE:

- in the BODY, what additional properties do you need (ie. the studentId? the teacherId)
- what AUTHENTICATION do you need -> can anyone call the API endpoint for these routes; 
- what if I am logged in as a STUDENT?

**Comment by d-username** [comment]
the teacherId will come from - from req.user.id - from the logged in user.
the stuentId will come from params - ie: profile/:id/notes

for AUTHENTICATION - inside the routes, we will ensure that only the Teacher can access these endpoints.
as a Student, you would not have the option on the Client-side to access notes.

**Comment by dogezen** [comment]
OK - maybe the req.user has a property that tells you the user type? And hence you return error if a STUDENT calls that endpoint? You cannot trust the CLIENT makes the correct API call.

**Comment by Alex90Jennings** [comment]
There is a validateTeacherRole that we can implement into the route. I believe if I student manually types in the URL for an endpoint that has the validateTeacherRole, they see a blank page.

Is this enough as a safeguard?
