### ISSUE TITLE
create Notes in Schema (SERVER) - [5]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#153]
## Story
As a teacher, I want to be able to add notes on individual students, and I want to be able to update the notes, I also want to see my name and the timestamp.

## Tasks
-  update Schema with the Notes model
-  students can have many notes, a note belongs to a student and to a teacher. 
 - each note must have a userId of a student and a userId of a teacher 
 - each note should have a column with a boolean value - if it is edited or not

**Comment by Alex90Jennings** [comment]
![image](https://user-images.githubusercontent.com/97463171/177317233-6d6e6bbc-f654-4759-82a2-11d7cae95fb4.png)

**Comment by Alex90Jennings** [comment]
https://github.com/boolean-uk/team-dev-server/pull/154
