### ISSUE TITLE
Teacher Can Add An Exercise To A Cohort (3)

### ISSUE THREAD

**Issue by Hoolio333** [boolean-uk/team-dev-server#157]
Issue linked to: [https://github.com/boolean-uk/team-dev-client/issues/235](url)

## Tasks

- End point for '/cohorts/5/exercises'
- cohortExercise Model with createdAt
- Cohort Model one to many relationship with cohortExercises
- Exercise Model one to many relationship with cohortExercises

## Check List
**Before PR**
- [ ] Have tested locally using ThunderClient/Postman/etc.
- [ ] For any new APIs, have documented in the README.md
- [ ] Have included and tested any required schema changes
- [ ] Have handled all error cases (try/catch, checked user input, etc.)
- [ ] Error messages are consistent with the rest of the code
- [ ] Correct HTTP Response codes and verbs are used
- [ ] Code confirms to the existing style and structure
- [ ] No warnings or errors are reported when using the API
- [ ] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [ ] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any required schema updates have been applied cleanly
- [ ] If modifying an existing API the client app already uses, have verified the deployed client app still works as expected

**Comment by Hoolio333** [comment]
As discussed with User Profile Team

**Comment by Alex90Jennings** [comment]
TEACHER CAN ADD AN EXERCISE TO THE COHORT

.post req in the cohort route
	req.body githubUrl, exerciseId (from res.body), cohortId (from params)

**Comment by dearshrewdwit** [comment]
Seems reasonable. 2 notes:

1. Given we're creating a CohortExercise, update the name for the resource in the end point to be `POST '/cohorts/5/cohortExercises'`
2. gitHub url and exerciseId are both extracted from the request body (not just github url)

**Comment by Alex90Jennings** [comment]
OK thanks Ed, will update our plan
