### ISSUE TITLE
Create Submissions table in Schema [2]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#158]
## Tasks

 - cohort exercise has many submissions, a submission belongs to a cohort exercise 
 - create Submission on the schema with one cohort to many submission relationships
 - the Submissions table should include these columns:  id (Int), CohortExercise (CohortExercise), CohortExerciseId (Int), User (User), UserId (Int), submitted (Boolean), createdAt (Date), updatedAt (Date)

**Comment by sigristarisa** [comment]
The plan:

- create a schema ``Submission`` in the schema file
- the ``Submission`` will include:
   id (Int)
   CohortExercise (CohortExercise) (one to many relationship)
   CohortExerciseId (Int)
    User (User) (one to many relationship)
    UserId (Int)
    isSubmitted (Boolean)
    createdAt (Date)
    updatedAt (Date)
    
   - update the schema
   
  *since team Teacher Admin is creating ``CohortExercise``, make sure the column name matches

**Comment by dearshrewdwit** [comment]
Great start. 2 points:

1. I need clarification for the `isSubmitted` property - what's the reasoning here?
2. I need clarification for how a teacher will be able to click a student submission and be taken to the **student's** github repository? I don't see any data stored for this - it is possible to use the student's githubUrl to find their username and build the link to the repo using the exercise repo url. It might be easier though to store the student github repo in the submissions table.

**Comment by dearshrewdwit** [comment]
1. This approach will mean you need to create a record in the submissions table for each student in the cohort as soon as a teacher adds an exercise to the cohort. Then when a student 'submits' their work, you would have to find the submission record and update the boolean value for `isSubmitted` from false to true. This is possible. 

My suggestion is to only create records in the submissions table when a student clicks the submit button, removing the need for the `isSubmitted` property. 

To display the available cohort exercises for a student, find all cohort exercises, and find all student submissions. Loop through the cohort exercises rendering them on the page. Add the 'submit button', and some styling depending if there's a corresponding submission or not.

**Comment by sigristarisa** [comment]
<img width="327" alt="Screenshot 2022-07-07 at 13 43 50" src="https://user-images.githubusercontent.com/90552887/177765592-4eeeb4e0-df62-4504-bc70-589ccfef9298.png">

1. Yes, your explanation makes sense – thank you!

2. Ok - yes we will then calculate the URL in the client app and relocate the user.

We've updated the diagram. If this is ok we will start creating the schema!

**Comment by dearshrewdwit** [comment]
Yes, LGTM

**Comment by dearshrewdwit** [comment]
@sigristarisa the work for this has been reverted. It needs a new PR. See the linked revert PR above
