### ISSUE TITLE
create Endpoints for cohortExcercises [8]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#159]
## Tasks

- UI :
    - navigate to '/profile/12/exercises'   - we want to get all the exercises for user 12 
- Server : 
    - add endpoint for /user/:userId/exercises  -  get all excercises by userId
    - add an endpoint  /user/:userId/submission/:excerciseId - this is to post a specific submission

**Comment by Creatorrr1** [comment]
<img width="845" alt="Screenshot 2022-07-08 at 12 14 51" src="https://user-images.githubusercontent.com/90321114/177982032-7da76263-d5f1-45b9-b5d6-b2e60df6d6a1.png">
This is our plan, what do you think about?

**Comment by Creatorrr1** [comment]
**

New Plan

** ->
<img width="920" alt="Screenshot 2022-07-11 at 12 27 42" src="https://user-images.githubusercontent.com/90321114/178254480-877b8bb3-7848-4c20-ba05-96ad9c2375aa.png">
