### ISSUE TITLE
handle Submission [5]

### ISSUE THREAD

**Issue by d-username** [boolean-uk/team-dev-server#160]
- adding a submission creates a cohort exercise submission
- form the JSON req body 
- ensure that the exercise domain persists on to DB

**Comment by sigristarisa** [comment]
- create an endpoint ``.post( /:id/submit)`` by using ``userRouter``
- take in ``userId`` from the url, and take in ``cohortExerciseId``from ``req.body``
-  check if ``cohortExerciseId`` exist in the body => if not, throw an error
- create a new domain exerciseSubmission.js that has two methods – create a submission, and save a submission
- return a response with the submission

**Comment by dearshrewdwit** [comment]
Nice. 2 notes: 

1. Let's invert the approach - use `POST '/cohortExercises/:id/submissions'` where the id is the cohortExercise id.
2. domain object name should be same as the model: `Submission`

**Comment by sigristarisa** [comment]
Thank you for the feedback.
Quick question – 

1. Let's invert the approach - use POST '/cohortExercises/:id/submissions' where the id is the cohortExercise id.
=> we will need ``userId`` for the submission, does this mean we will get ``userId``from ``req.body`` and ``cohortExerciseId``from the url?

2. Yes, we will make that change!

**Comment by sigristarisa** [comment]
Confirmed by @dearshrewdwit – get ``userId`` from ``req.body`` and ``cohortExerciseId``from from the url
