### ISSUE TITLE
#27 As a teacher, so I can begin onboarding a new class, I want to create cohorts.

### ISSUE THREAD

**Issue by richard-mattinson** [boolean-uk/team-dev-server#209]
## User Story
As a teacher, so I can begin onboarding a new class, I want to create cohorts.

- Add a new "Create cohort" button to the application. This should be displayed for teachers only.
- For now, all the button needs to do is create a new Cohort, there is no other information required.
- This may require adding the ability to register as either a teacher or a student. For now, we can just add a simple radio button selection on the sign up for. Later we'll implement something more sophisticated.

## Tasks
**SERVER**
- Create a dummy teacher account to test with
- Refactor fromJSON method in User class to accept role parameter
- Add role parameter from json method in the user class
- If role is checked create as teacher, if null or undefined default to student
- use validateTeacherRole function
- Teacher can then click button which will send a post request to `/cohort`. (No data required only auth header)
- [Response Example](https://hubertlemczak.github.io/team-dev-api/#/cohort/createCohort)

**Comment by Auenc** [comment]
> This should be displayed for teachers only.
Might be a good idea to write how you will check if a user is a teacher or not.

> For now, all the button needs to do is create a new Cohort, there is no other information required.
It would be good if you can add a bit of detail as to how clicking the button will create the cohort. For instance, is it calling an API? If so, what endpoint is it calling? Does it need to pass any data to that endpoint etc. 

It's great you'e added an example response, but it might also be a good idea to add an example request
