### ISSUE TITLE
#31 As a user, so I can share my progress with others and take part in the community, I want to be able to make posts

### ISSUE THREAD

**Issue by miresque** [boolean-uk/team-dev-server#212]
## User Story
As a user, so I can share my progress with others and take part in the community, I want to be able to make posts

## Tasks
- Modify the post model in the prisma schema by adding createdAt & updatedAt fields(https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#updatedat):
![posts_model_update](https://user-images.githubusercontent.com/62182881/189929239-59b6f4ea-4668-46de-a62f-5a824edda55d.png)
- Check for authentication middleware and requests sent for the {URL}/post route(http://expressjs.com/en/guide/routing.html).
- Modify the create function in the post controller to handle the request ``(request header: { Authorization: Bearer <token> }, request body: { "content": "" })`` and check for any missing fields in the body. 
- Then using the 'create' prisma query(https://www.prisma.io/docs/concepts/components/prisma-client/crud#create), with the content from the request, the function will add an entry into the DB.
- Send the corresponding response back to the client: 
``return res.status(201).json({ status: 'success', data: content }) <for a successful request>``
``return res.status(statusCode).json({ status: 'fail', error: "missing fields in body" })  <for a failed request>``

**Comment by Auenc** [comment]
Looks good to me!
