### ISSUE TITLE
#32 As a teacher, so I can organise our students, I want to assign students to a cohort

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-server#213]
## User Story
As a teacher, so I can organise our students, I want to assign students to a cohort.

## Tasks

# SERVER
- Create new endpoint `get /cohort` to retrieve a list of all cohorts
- Create new update user method to add to cohort
- Add student by id to cohort by cohort_id
- Retrieve student id from request params
- Retrieve cohort_id from request body
- Responds with successful response or error [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/user/asd)

**Comment by Auenc** [comment]
Looks good to me!
