### ISSUE TITLE
#63 As a user, so I can show my appreciation of comments, I want to like them

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-server#260]
### Tasks
- Prisma schema add like relation to comment
- Create CommentLike model to accomodate comment likes
   - Make postId and commentId nullable
   - [ERD Diagram](https://whimsical.com/erd-XH5wCi5YHAc2zMc29vQWBc)
- Create `post /post/:postId/comment/:commentId/like` endpoint
   - Create `createCommentLike` controller 
- Create `delete/post/:postId/comment/:commentId/like` endpoint
    - Create `deleteCommentLike` controller

**Comment by vherus** [comment]
Nice. Go ahead!
