### ISSUE TITLE
#62 As a user, so I can engage in conversation, I want to comment on comments

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-server#263]
### Tasks

- Create self-relation in Comment model [ERD](https://whimsical.com/erd-XH5wCi5YHAc2zMc29vQWBc)
- Edit `createComment` controller to accept parentId
- Add replies to seed
- [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/post/commentPost)

**Comment by Auenc** [comment]
Can you add some detail such as example JSON data of comments having comments, as well as the request data for commenting on a comment

**Comment by Auenc** [comment]
Approved :)
