### ISSUE TITLE
 As a user, so I can leave the course, I want to deactivate my account #69

### ISSUE THREAD

**Issue by ning905** [boolean-uk/team-dev-server#292]
- Add a new column isActive (Boolean, default as true) on the User table.
- Modify src/domain/user.js to include the isActive property in the User class.

Check user login details:
- When a user first clicks on the “Deactivate my account” button, they will be asked to enter their login details. Then a POST request will be sent to “http://localhost:4000/user/id”, with the login details as the body. 
- The server receives the request, run validateAuthentication check
If it fails, return error message respectiveIy.
- If passes, find a user in the DB with the id from req.params. 
	- If not found, return error 404
	- If found, compare req.params.id with req.user.id
		- If fails, return error 403
- If passes, hash the password sent in the body, compare the password and email with foundUser.password and foundUser.email.
	- If fails, return error 400
	- If passes, return the foundUser, excluding the password.

Deactivate account:
- If the user then confirms to deactivate their account, a PATCH request will be sent to the server with an endpoint of “http://localhost:4000/user/id”. 
- The server receives the request, run validateAuthentication check, if it fails, return error message respectiveIy.
- If the request passes the validation state, the request object should have a user property, where we could know the id.
- Try to find a user in the DB with the id from req.params. 
	- If not found, return error 404
	- If found, compare req.params.id with req.user.id
		- If fails, return error 403
		- If pass, update the user with the provided key and value.  
		

Team Post Plan: 
- [ ] Add isActive (Boolean? @default(true)) to the `User` model
   - [ ] When a user deactivates their account isActive will be false
- [ ] Update `getAll` posts controller to not include deactivated account likes
- [ ] Create formatting function that will replace data to be sent to client with `[removed]` for deactivated accounts
   - [ ] If `req.user.role` is TEACHER or ADMIN then original data will be sent to client
   - [ ] If `req.user.role` is STUDENT then formatted data will be sent to client

**Comment by vherus** [comment]
This seems like a good breakdown. Go ahead with this

**Comment by ning905** [comment]
In check user login details process, final step, instead of returning the user's data, the server will simply return a "success" message.
