### ISSUE TITLE
Dashboard (server)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-server#3]
> As a user,
So I can have easy access to everything,
I want to see a dashboard filled with posts after logging in.

**Requirements**

- Bearer token required to access this resource

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "posts": [
      {
        "id": int,
        "content": string,
        "author": {
          "id": int,
          "cohort_id": int | null,
          "first_name": string,
          "last_name": string,
          "role": string<"STUDENT", "TEACHER">,
        }
      }
    ]
  }
}
```

**4xx Client error response body**
```json
{
  "status" : "fail",
  "data" : {
    "authentication": "Invalid or missing access token"
  }
}
```

**5xx Server error response body**
```json
{
  "status": "error",
  "message": "Unable to communicate with database"
}
```

**Comment by d-username** [comment]
We have made a plan for the implementation.
Bulletpoints are below:

➡️  to be able to test this step, first we need to make sure the Create Post works
➡️  route "/posts" 
➡️  make a call to prisma to get all posts
➡️  const post = await prisma.post.findMany()
➡️  we want to sort posts in order of creation - to be able to do this we need to update Prisma, must include CreatedAt & UpdatedAT.
➡️  authentication of Bearer token is handled already by middleware.
➡️  error handling - we  add a try/catch just in case, in case no posts in DB the dashboard will be empty.
➡️  on Client Side when displaying posts we use .map() - it only works on arrays - from Server we must make sure the response is correctly formatted as Array.

**Comment by dogezen** [comment]
What type of request is it for route "/posts": GET, POST, ...?
Where will the call to prisma happen? In the route or controller?
Do you want to return ALL posts or up to a certain limit ? Ie 20? (pagination)
Good idea with sorting posts by created date -> see if your PRISMA instruction can be altered to be given an order by option.
