### ISSUE TITLE
Fix: Current pinned post check 

### ISSUE THREAD

**Issue by richard-mattinson** [boolean-uk/team-dev-server#300]
## Issue
- Currently pinned post can't be unpinned as they are caught in a check that stops the user from pinning multiple posts. This causes the user to receive a `This user already has a pinned post` error when attempting to unpin their post. 
## Fix
- Add `id: { not: postId }` to allow the currently pinned post to update if it is passed to the `setIsPinned` function.

**Comment by vherus** [comment]
Approved
