### ISSUE TITLE
Create a post (server)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-server#4]
> As a user,
So I can be a social butterfly,
I want to update others on my activities.

**Note**
This has been partially implemented (https://github.com/boolean-uk/team-dev-server/issues/17)
- Auth is fully implemented
- The Prisma model / migration is implemented
- The API response is hard coded, needs hooked up to real data

**Requirements**

- Bearer token required to access this resource

**201 Response body**
```json
{
  "status": "success",
  "data": {
    "post": {
      "id": int,
      "content": string
    }
  }
}
```

**4xx Client error response body**
```json
{
  "status" : "fail",
  "data" : {
    "authentication": "Invalid or missing access token",
    "content": "Must provide content to post"
  }
}
```

**5xx Server error response body**
```json
{
  "status": "error",
  "message": "Unable to communicate with database"
}
```

**Comment by Hoolio333** [comment]
Plan (All four of us to do this together to start with):

- Require JWT
-  JWT Secret 
- complete the create async (post) function:
- create post (await prisma)
- If error "must provide content" or proceed
- If error "wrong user id" or proceed
- Verify Token
- if error "invalid token" or proceed
- send back the data (res.json({ data: create });
- module export the function

**Comment by dogezen** [comment]
Team, that's a good starting point, would be great to break it down a bit further in terms of Routes, Controller, Services, see here:

1. Route: routes/post.js, see `router.post('/', validateAuthentication, create)` - already implemented for us
2. Auth Validation to verify bearer token: use validateAuthentication from middleware/auth.js - already implemented

Implement Create Post Controller method
1. extract body
2. validate that body has the correct content/data , return error if not
3. make a call to PRISMA to create a POST for this user
4. report back any errors from PRISMA or
5. if POST created in PRISMA; return back the expected data

**Comment by dogezen** [comment]
You could even go into a bit more detail for a few steps:

For example, in the extract body -> what are the parameters you expect; are there any requirements on these parameters (ie. minimum text length, etc)?

**Comment by Hoolio333** [comment]
Our code which works after testing on insomnia:

Successful post - works
Error when no content - works
Access token Error - works 

```
import { sendDataResponse } from '../utils/responses.js'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

export const create = async (req, res) => {
  const { content } = req.body
  if (!content) {
    return sendDataResponse(res, 400, { content: 'Must provide content' })
  }
  try {
    const post = await prisma.post.create({
      data: {
        content,
        userId: req.user.id
      }
    })
    return sendDataResponse(res, 201, { ...post })
  } catch (err) {
    return res.status(400).json({ err: err.message })
  }
}

```
Testing success on insomnia:

![Insomnia Post Create Success](https://user-images.githubusercontent.com/98411345/175093096-ee703cfc-2054-4aa5-89fa-68087c4459e2.png)
