### ISSUE TITLE
Add user to cohort (server)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-server#8]
> As a teacher,
So I can organise our students,
I want to assign students to a cohort.

**Requirements**

- Bearer token required to access this resource
- Only teacher roles can perform this action

**200 Response body**
```json
{
  "status": "success",
  "data": {
    "user": {
      "cohort_id": int | null
    }
  }
}
```

**4xx Client error response body**
```json
{
  "status" : "fail",
  "data" : {
    "authentication": "Invalid or missing access token",
    "authorization": "You are not authorized to perform this action",
    "cohort_id": "Cohort ID must be an integer",
    "cohort_id": "Cohort could not be found"
  }
}
```

**5xx Server error response body**
```json
{
  "status": "error",
  "message": "Unable to communicate with database"
}
```

**Comment by Alex90Jennings** [comment]
![image](https://user-images.githubusercontent.com/97463171/175959437-69bb65ad-9dda-445c-b473-6bcb6fb94453.png)

**Comment by Alex90Jennings** [comment]
https://github.com/boolean-uk/team-dev-server/pull/118

**Comment by Alex90Jennings** [comment]
https://github.com/boolean-uk/team-dev-server/commit/8ebac85caf7be03aabf17e44c9faa55072262003
